[package]
name = "hashtest"
version = "0.2.0"
authors = ["jlgerber <jlgerber@gmail.com>"]
edition = "2018"

[dependencies]
blake2 = "0.9.0"
hex = "0.4.2"
structopt = "0.3.17"
thiserror = "1.0.20"
lazy_static = "1.4.0"

[dev-dependencies]
serial_test = "0.5.0"